### ISSUE TITLE
UI Configuration access or change - 

### ISSUE THREAD

**Issue by madmotor1** [SolardiaX/DarkUI#1]
How to access things like spellbook and or just to get to default in game items . default things to adjust.  is ther e like a /darkUI or some other spelling to get to the configurations pages etc..?  I love it so far just difficult to find some settings or how to.

**Comment by SolardiaX** [comment]
In game press esc to open game menu, there a botton named `DarkUI`, click it to open the addon configuration page.

**Comment by madmotor1** [comment]
I did not even see it, thank you for pointing it out.  I commend this UI very much, very clean install, very clean looking, very easy and straight forward to adjust in configs.  Overall You did great, thank you ))
