### ISSUE TITLE
UI Configuration access or change

### ISSUE THREAD

**Issue by McBParker** [SolardiaX/DarkUI#2]
Hey Just updated to the latest version of Dark UI, when I hit escape there is no option for the Dark UI menu to make edits, did you change how this is accessed?
![2024-08-30_10h50_49](https://github.com/user-attachments/assets/5fcf9b24-80fa-4a9f-9dc2-10aba8e91d06)

**Comment by SolardiaX** [comment]
Fixed in version 11.0.2-b1.0.5a1
