### ISSUE TITLE
b1.0.5

### ISSUE THREAD

**Issue by Hiffix** [SolardiaX/DarkUI#3]
There is no folder DarkUI_options i last build!

How do i disable right side action bars? There is no option in DarkUI and WoW thingy is also not working for it.

Is there way change font for chat/data texts?

Hvb is not working generating mass errors:

 

2x ...rfaceDarkUI/Modules/ActionBar/SetBinding.lua:312: attempt to index local 'b' (a nil value)

[string "@DarkUI/Modules/ActionBar/SetBinding.lua"]:312: in function `?'

[string "@Blizzard_ChatFrameBase/Mainline/ChatFrame.lua"]:5468: in function `ChatEdit_ParseText'

[string "@Blizzard_ChatFrameBase/Mainline/ChatFrame.lua"]:5120: in function <Blizzard_ChatFrameBase/Mainline/ChatFrame.lua:5119>

[string "=[C]"]: in function `ChatEdit_SendText'

[string "@Blizzard_ChatFrameBase/Mainline/ChatFrame.lua"]:5156: in function `ChatEdit_OnEnterPressed'

[string "*ChatFrame.xml:140_OnEnterPressed"]:1: in function <[string "*ChatFrame.xml:140_OnEnterPressed"]:1>

 

Locals:

elapsed = 0

(for index) = 1

(for limit) = 12

(for step) = 1

i = 1

b = nil

(*temporary) = "SpellButton1"

(*temporary) = nil

(*temporary) = "OnEnter"

(*temporary) = true

(*temporary) = 122629

(*temporary) = "Button"

(*temporary) = "12"

(*temporary) = "attempt to index local 'b' (a nil value)"

L = <table> {

 DATATEXT_SECOND = "S"

 LOOT_MONSTER = ">> Loot from "

 DAMAGEMETER_OPTION_SPACING = "Bar spacing"

 DAMAGEMETER_OPTION_SAVE_ONLY_BOSS_FIGHTS = "Only save Boss fighting infomation"

 ACTIONBAR_AP_NAME = "Equip"

 ACTIONBAR_BINDING_DISCARDED = "All newly set keybindings have been discarded"

 ACTIONBAR_BINDING_MODETEXT = "Hover your mouse over any actionbutton to bind it. Press the escape key or right click to clear the current actionbutton's keybinding"

 BAG_HINT_RESET_NEW = "Reset New"

 DATATEXT_GARBAGE_COLLECTED = "Garbage collected"

 MAP_HIDE_TASK_POI = "Hide task POI"

 MAP_PLAYER = "Player"

 AURA_CRIT = "CRIT"

 AURA_VERSA = "VERSA"

 MAIL_ENVFULL = "Env is full"

 ACTIONBAR_AP_UPGRADE = "Upgrade"

 TOOLTIP_ACH_COMPLETE = "Status: Complete "

 DATATEXT_TOTAL_CPU_USAGE = "Total CPU Usage:"

 LOOT_CHEST = ">> Loot from chest"

 ACTIONBAR_BINDING_DISCARDEBTN = "Discard"

 DATATEXT_MEMORY_USAGE = "UI Memory Usage:"

 BAG_BAGCAPTIONS_BANKSETS = "Item Sets"

 DAMAGEMETER_OPTION_BAR_WIDTH = "Bar width"

 DATATEXT_MINUTE = "M"

 UNITFRAME_AFK = "[AFK]"

 CHAT_INTERRUPTED = "Interrupted: %s - |cff71d5ff|Hspell:%d:0|h[%s]|h|r！"

 DATATEXT_MILLISECOND = "ms"

 DAMAGEMETER_OPTION_MERGE_HEAL_AND_ABSORBS = "Merge heal and absorbs"

 AUTO_REPAIR_GUIDE_INFO = "Repair from guild bank "

 TOOLTIP_LOADING = "Loading..."

 COMBATTEXT_TEST_DISABLED = "Combat text test mode disabled."

 AURA_MOVE = "MOVE"

 CHAT_RAID_WARNING = "RW"

 BAG_GEM = "Gem"

 COMBATTEXT_UNLOCKED = "Combat text unlocked."

 TOOLTIP_ITEM_ID = "ItemID:"

 MAP_MOUSEOVER = "Mouse"

 LOOT_TO_GUILD = "  Guild"

 BAG_RESTACK = "Restack"

 DATATEXT_HOUR = "H"

 AURA_MASTERY = "MASTERY"

 UNITFRAME_GHOST = "Ghost"

 AUTO_INVITE_INFO = "Accepted invite from "

 MAIL_MESSAGES = "New mail"

 ACTIONBAR_APB = "APB"

 AURA_CAST_BY = "CastBy"

 ACTIONBAR_BINDING_BINDING = "Binding"

 DATATEXT_HIDDEN = "Hidden"

 ACTIONBAR_BINDING_SAVEBTN = "Save"

 DATATEXT_SESSION_GAIN = "Session Gain/Loss"

 COMBATTEXT_TEST_USE_TEST = "Type /xct test to toggle combat text testmode."

 AURA_GET_CLOSE = "GET CLOSE"

 TOOLTIP_WHO_TARGET = "TargetBy"

 CHAT_GUILD = "G"

 AURA_STRIKE = "STRIKE"

 COMBATTEXT_TEST_USE_RESET = "Type /xct reset to restore default positions."

 AURA_ATTACKSPEED = "ATTACKSPEED"

 TOOLTIP_ACH_STATUS = "Status:"

 ACTIONBAR_PARAGON_EXP = "Paragon Exp"

 DAMAGEMETER_OPTION_BAR_COLOR = "Bar color"

 DATATEXT_SERVER_GOLD = "Server Gold"

 CHAT_RAID_LEADER = "RL"

 TOOLTIP_NO_TALENT = "No Talent"

 LOOT_TO_RAID = "  Raid"

 ACTIONBAR_BINDING_ALLCLEAR = "|cff00ff00%s|r All keybindings have been cleaned"

 CHAT_GM = "[GM]"

 ACTIONBAR_BINDING_INCOMBATLOCKDOWN = "Can't set key binding in combat"

 BAG_BAGCAPTIONS_STUFF = "Stuff"

 CHAT_INSTANCE_CHAT_LEADER = "IL"

 BAG_BAGCAPTIONS_GEM = "Gems"

 DATATEXT_AUTO_REPAIR = "AutoRepair"

 TOOLTIP_ITEM_COUNT = "Count:"

 BAG_RESETCATEGORY = "Reset Category"

 CHAT_DND = "[DND]"

 DAMAGEMETER_OPTION_FONT_SIZE = "Font size"

 DATATEXT_DAY = "D"

 AURA_CD = "COOLDOWN"

 ACTIONBAR_BINDING_TRIGGER = "Trigger"

 BAG_BAGCAPTIONS_KEYRING = "Keyring"

 BAG_CONSUMABLES = "Consumable"

 DATATEXT_DOWNLOAD = "Down:"

 COMBATTEXT_ALREADY_LOCKED = "Combat text is already locked."

 ACTIONBAR_BINDING_BINDTO = "|cff00ff00 %s is binding to %s |r"

 BAG_BATTLEPET = "Battle Pets"

 BAG_BAGCAPTIONS_BATTLEPET = "Battle Pets"

 BAG_BAGCAPTIONS_TRADEGOODS = "Reagents"

 DAMAGEMETER_OPTION_BORDER_COLOR = "Border color"

 AUTO_INVITE_KEYWORD = "inv"

 PANELS_AFK_LCLICK = "Left-Click to go back."

 DAMAGEMETER_CURRENT = "Current"

 WELCOME_LINE = "Welcome to DarkUI "

 BAG_BAGCAPTIONS_QUEST = "Quest Items"

 ACTIONBAR_BINDING_KEY = "Key"

 BAG_BAGCAPTIONS_ARMOR = "Equipment"

 DATATEXT_TOTAL_MEMORY_USAGE = "Total Memory Usage:"

 AUTO_DECLINE_DUEL_PET_INFO = "Declined pet duel request from "

 BAG_BAGCAPTIONS_ITEMSETS = "Item Sets"

 TOOLTIP_INSPEC

**Comment by SolardiaX** [comment]
Fixed in version 11.0.2-b1.0.5a1
