### ISSUE TITLE
Framedrop and Freezes

### ISSUE THREAD

**Issue by Marih-GitHub** [SolardiaX/DarkUI#5]
Great interface, I really like it.

But every few seconds I get a 10/15 frame drop causing tearing on the screen.

Since I started using it WOW randomly freeze in Instances.

Disabling DarkUI the problem disappear.

Thank you for your attention.

**Comment by SolardiaX** [comment]
Hi, thanks for your feed back. Please use BugSack + BugGrabber to collect script errors if there have and put them back here.

**Comment by Marih-GitHub** [comment]
Starting testing in Dungeons.
These are the first errors (just started so no freeze).
[DarkUI Errors.txt](https://github.com/user-attachments/files/17055706/DarkUI.Errors.txt)
Later I will add more addons.

Update: First time I was able to finish an Instance without freezes.

Second Update: Game Freezed 3 Times on the last Boss of the Delve "Mycomancer Cavern". I had to turn off DarkUI to finish the Instance.
[DarkUI Errors 2.txt](https://github.com/user-attachments/files/17062429/DarkUI.Errors.2.txt)

**Comment by SolardiaX** [comment]
Hi, looks like some other addons conflict with DarkUI such as TipTac and try again, and please list all your enabled addons here.

**Comment by Marih-GitHub** [comment]
I reduced the number of Addons. Did a couple of Dvelves without any freezing.
I see that the short frame drop (for about 1 second) and screen tearing happen when Zygor Guide or DugiGuide are enabled (not both at the same time of course). This happen usually when exiting combat.
Do you know a tool that can create a text list of my actual addons?
Thank you for you patience.

**Comment by SolardiaX** [comment]
> I reduced the number of Addons. Did a couple of Dvelves without any freezing. I see that the short frame drop (for about 1 second) and screen tearing happen when Zygor Guide or DugiGuide are enabled (not both at the same time of course). This happen usually when exiting combat. Do you know a tool that can create a text list of my actual addons? Thank you for you patience.

Screen shot of your in game settings for addons enable/disable is OK.

**Comment by Marih-GitHub** [comment]
I can confirm that the the total blocking of the WOW client occurs only when the Zygor Guide is loaded in the Addons.
I can't say if it's a code incompatibility or a question related to the amount of memory used by the Addons.
The Zygor Guide takes up approximately 250 mega of memory and therefore the increase that occurs when it is loaded is notable.

**Comment by Marih-GitHub** [comment]
When I disable the Target Arrow, the other nameplates turn to white.
Is it only me?

**Comment by SolardiaX** [comment]
> When I disable the Target Arrow, the other nameplates turn to white. Is it only me?

Yeah, it's a bug. I'll fix soon.

**Comment by Marih-GitHub** [comment]
By the way, these are the addons that I use with DarkUI
![Screenshot (340)](https://github.com/user-attachments/assets/f90d2fb4-6e11-4cb9-b6dc-aa96c4790c3c)
![Screenshot (341)](https://github.com/user-attachments/assets/4cba2fb7-5e4f-4ea9-a7b7-8c25f145bddb)
![Screenshot (342)](https://github.com/user-attachments/assets/67e2bbe0-80d6-4d18-befa-9520606992a6)
![Screenshot (343)](https://github.com/user-attachments/assets/fc282edf-3506-444f-af13-cee9155fba44)
![Screenshot (344)](https://github.com/user-attachments/assets/bb56ad68-17ce-44ba-a082-99998cabee13)
![Screenshot (345)](https://github.com/user-attachments/assets/9038e917-c1a9-4dbe-80b4-b86132f77d98)
![Screenshot (346)](https://github.com/user-attachments/assets/00d7ee5a-ee38-4801-bce2-09e3ee14f047)
